version: '3.8'

services:
  vue-app:
    build: .
    ports:
      - '5174:80'
    volumes:
      - .:/app
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge
